In [2]:
#operatioins on Ndarray
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
#adding array A and B
print("Elementwise sum of array A and B is :\n",A+B)
            

Elementwise sum of array A and B is :
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [15]:
import numpy as np
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x.shape

(3, 4)

In [4]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [5]:
x.strides

(16, 4)

In [6]:
x.ndim

2

In [7]:
x.data

In [8]:
x.size

12

In [9]:
x.itemsize

4

In [10]:
x.base

In [11]:
x.nbytes

48

In [12]:
x.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [13]:
x.real

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
x.imag

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])